modLoader="javafml"

loaderVersion="[46,)" 

license="All Rights Reserved"

issueTrackerURL="https://github.com/addavriance/terramath/issues"

[[mods]]
modId="terramath"
version="${version}"

displayName="TerraMath"
displayURL="https://www.curseforge.com/minecraft/mc-mods/terra-math/"

logoFile="icon.png"
authors="addavriance"

description='''
Generate your Minecraft worlds using mathematical formulas! Create unique terrains from waves to spirals with custom equations.
'''

[[dependencies.terramath]]
   modId="forge"
   mandatory=true
   versionRange="[46,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.terramath]]
   modId="minecraft"
   mandatory=true
   
   versionRange="[1.20,1.20.1]"
   ordering="NONE"
   side="BOTH"

[modproperties.terramath]
   catalogueItemIcon="minecraft:repeating_command_block"
